[package]
name = "kokona"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
discord-rich-presence = "0.2.5"
eframe = "0.30.0"
egui = "0.30.0"
rfd = "0.15.2"
