name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            
      - name: Install Rust toolchain (Apple Silicon)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
          
      - name: Build for mac
        run: cargo build --release --target aarch64-apple-darwin

      - name: Create Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kokona-darwin-arm
          path: target/aarch64-apple-darwin/release/kokona-darwin-aarch64
