name: Rust

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".github/workflows/rust.yml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-release-

      - name: Install Rust toolchain (Apple Silicon)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Build for mac (Release)
        run: cargo build --release --target aarch64-apple-darwin

      - name: Upload Mac Build (Release)
        uses: actions/upload-artifact@v4
        with:
          name: kokona-darwin-aarch64-release
          path: target/aarch64-apple-darwin/release/kokona
          compression-level: 0

  build-mac-debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-debug-

      - name: Install Rust toolchain (Apple Silicon)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Build for mac (Debug)
        run: cargo build --target aarch64-apple-darwin

      - name: Upload Mac Build (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: kokona-darwin-aarch64-debug
          path: target/aarch64-apple-darwin/debug/kokona
          compression-level: 0

  build-windows-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-debug-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build for Windows (Debug)
        run: cargo build --target x86_64-pc-windows-gnu

      - name: Upload Windows Build (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: kokona-windows-x86_64-debug
          path: target/x86_64-pc-windows-gnu/debug/kokona.exe
          compression-level: 0

  build-windows-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-release-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build for Windows (Release)
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Windows Build (Release)
        uses: actions/upload-artifact@v4
        with:
          name: kokona-windows-x86_64-release
          path: target/x86_64-pc-windows-gnu/release/kokona.exe
          compression-level: 0

  build-linux-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-debug-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build for Linux (Debug)
        run: cargo build --target x86_64-unknown-linux-gnu

      - name: Upload Linux Build (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: kokona-linux-x86_64-debug
          path: target/x86_64-unknown-linux-gnu/debug/kokona
          compression-level: 0

  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.OS }}-build-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-release-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build for Linux (Release)
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload Linux Build (Release)
        uses: actions/upload-artifact@v4
        with:
          name: kokona-linux-x86_64-release
          path: target/x86_64-unknown-linux-gnu/release/kokona
          compression-level: 0
